### PR TITLE
Add make build-deb target

### PR DESCRIPTION
**Pull request by c-nixon**
Add a build-deb target to Makefile to allow us to generate deb file

### CODE REVIEW

**Comment by jmoses** [comment]
Is the cdn going to end up using this target, instead of it's whatever?

**Comment by jmoses** [comment]
```
Generating deb package for version 3.3.0-beta.1 as 3.3.0-beta.1-1
chmod: cannot access 'logdna-agent': No such file or directory
{:timestamp=>"2021-11-08T21:18:22.494223+0000", :message=>"Invalid package configuration: Cannot chdir to '/build/target/x86_64-unknown-linux-gnu/release'. Does it exist?", :level=>:error}
make: *** [build-deb] Error 1
```

**Comment by c-nixon** [comment]
`BUILD_VERSION=<some deb version> FEATURES= STATIC=1 make build-deb` should get it working properly for you

**Comment by c-nixon** [comment]
For the cdn... I'm not sure, I don't think there's a disadvantage, but I'll need to push the deb to s3 or somewhere for the cdn to pick up when it builds it's image.

**Comment by jmoses** [comment]
2021-11-09 at 10 33 AM

**Review by jmoses — APPROVED** [review]
It built me a working deb

**Pull request merged**
