### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by tanberry**
docs: edited the example in the Readme to remove specific version numbers.

### CODE REVIEW

**Review by c-nixon — APPROVED** [review]
This looks good to me, @alfeng6 is it clear enough for you?

**Comment by alfeng6** [comment]
now that we have the example be `git checkout major.minor.patch-beta.n`, we should make sure to link the dockerhub page to all the possible tags so they know what they can try out.

**Review by alfeng6 — CHANGES_REQUESTED** [review]
can we add a link to the dockerhub tags so it's clear for a user what tags they can checkout?

**Comment by c-nixon** [comment]
For this command the link to dockerhub might be confusing, the date/hash image tags aren't present in git, they're docker only. Maybe a link up to the github releases? Or just an instruction to run `git tag -l `to see what tags are available?

**Comment by tanberry** [comment]
@alfeng6 In the readme.io docs  added a link to the GitHub list of releases, and in the GitHub README.md file I added a sentence about using suggestion from @c-nixon for the `git tag -l` command to view all available releases. Take a look and let me know if those changes work, please.

**Comment by tanberry** [comment]
@alfeng6 can you take a look again at the Readme.md and review/tweak/approve, so that we can merge?

**Review by alfeng6 — APPROVED** [review]
looks great!

**Review by alfeng6 — APPROVED** [review]
thanks for the extra change!

**Pull request merged**
